// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5jYHAFcko2hWBmacllUiXHB2KjCkejM4',
    appId: '1:690121051237:web:507fa4610f84c658dd0a8c',
    messagingSenderId: '690121051237',
    projectId: 'newblog-b8aa8',
    authDomain: 'newblog-b8aa8.firebaseapp.com',
    storageBucket: 'newblog-b8aa8.appspot.com',
    measurementId: 'G-JZFST93P6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5hiUbs6DhIax14cTTojvY5A8JtGVbtBY',
    appId: '1:690121051237:android:d34a98f7e6cfe577dd0a8c',
    messagingSenderId: '690121051237',
    projectId: 'newblog-b8aa8',
    storageBucket: 'newblog-b8aa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACTo14q8iW8TPAolBvNxISTUcGlKf7NcA',
    appId: '1:690121051237:ios:a15855008a09fbe8dd0a8c',
    messagingSenderId: '690121051237',
    projectId: 'newblog-b8aa8',
    storageBucket: 'newblog-b8aa8.appspot.com',
    iosBundleId: 'com.example.newsBlogFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACTo14q8iW8TPAolBvNxISTUcGlKf7NcA',
    appId: '1:690121051237:ios:a61ed46df341a31edd0a8c',
    messagingSenderId: '690121051237',
    projectId: 'newblog-b8aa8',
    storageBucket: 'newblog-b8aa8.appspot.com',
    iosBundleId: 'com.example.newsBlogFlutterApp.RunnerTests',
  );
}
